### ISSUE TITLE
Update baybe/examples/Basics /campaign.py and baybe/examples/Serialization /basic_serialization.py

### ISSUE THREAD

**Issue by mgreiner79** [emdgroup/baybe#121]
In  baybe/examples/Basics /campaign.py, on line 80 `recommendation = campaign.recommend(batch_size=2)`.
The argument to campaign.recommend has been changed to `batch_quantity`.
Please update the example.

This is also a problem in baybe/examples/Serialization /basic_serialization.py on lines 97, 98.

**Comment by Scienfitz** [comment]
Hi @mgreiner79 

I'm not sure if I can follow, can you be more specific about the versions your looking at? are you on main or 0.7.2 ?

`batch_quantity` has been renamed to `batch_size` but that happened after version `0.7.2` and is still unreleased, this means the doc will still show the state of 0.7.2

We are working on having also a versioned documentation so you can always see the doc for `latest` as well as all published versions

A quick search shows me that the current main does not have unwanted occurrences of `batch_quantity`

**Comment by AdrianSosic** [comment]
Hi @mgreiner79 and @Scienfitz,

I think there is perhaps some confusion here, probably caused by the fact that we do not yet have a versioned documentation yet as @Scienfitz pointed out (which will hopefully come soon).

To quickly resync everyone:
* `batch_size` is indeed the **_new_** keyword. `batch_quantity` has been **_deprecated_** on the current `main` branch, but the change has not yet been released. Hence, the change is not yet visible on our online documentation.

So I'm now also trying to understand how @mgreiner79 ran into the issue. I suspect he used a version from `main` (e.g. via git-install) but then executed the code that was shown in the docs? And because the docs still show `batch_quantity`, he concluded that this is the new keyword? @mgreiner79: could you quickly confirm, or perhaps help us understand how you ran into the error?

FYI: Our examples and code snippets in the documentation are always automatically tested against the respective code version, ensuring that they can be executed without problems. So there is only little chance that something is inconsistent between code and doc. (Note: your issue #120 is in fact an exception since this was a problem related to the environment, not the code). But perhaps you found another edge case, so I'd really appreciate if you could help us find the root cause 🙃

**Comment by AdrianSosic** [comment]
Turned out the problem was due to using code from `0.7.2` but running the examples from the latest `main` branch, which already included the renaming. Probably, multi-version docs will help to avoid running into these problems in the future.
