### ISSUE TITLE
Batch_size error 

### ISSUE THREAD

**Issue by CatSci** [emdgroup/baybe#164]
Hi,

I am getting this error "TypeError: Campaign.recommend() got an unexpected keyword argument 'batch_size'". I am attaching snapshot for your reference. Could you please help me to sort this error out because till yesterday it was working fine.

![error](https://github.com/emdgroup/baybe/assets/107863185/1ffd2487-e955-4487-8d13-56d5da5ccd47)

**Comment by AVHopp** [comment]
Hello @CatSci, thanks for your question!

Could you maybe specify how you used and installed the package? That is, did you install via `pip`, did you install the latest version directly from the repository and which python version are you using?

**Comment by AVHopp** [comment]
Also, some other user experienced this as well, and it turned out that the reason was in fact a de-sync between the installed version of the package itself and the executed files. So you might also want to have a look here #121 and see if this happens to be related to your issue.

**Comment by CatSci** [comment]
Thanks, I am using `campaign.from_json()` and then using `campaign.recommend()`. I will keep you updated. 

![image](https://github.com/emdgroup/baybe/assets/107863185/81e7b6cb-9c90-419e-b2d2-a710bca47da4)

**Comment by Scienfitz** [comment]
Hi @CatSci the keyword `batch_size` of `recommend` was just recently introduced as renaming of the old keyword `batch_quantity`, please verify that you have a version > 0.7.2 installed since this deprecation happened there. Can you confirm which `baybe` version exactly is installed?

Also, since the old keyword was `batch_quantity` and our `recommend` function still has a `batch_quantity` keyword (for deprecation reasons) I would prob also try and rename the keyword `batch_quantity` to something else in your scripts to be absolutely 100% safe

**Comment by CatSci** [comment]
Thanks, I will check the version and other recommendations from your side.

**Comment by CatSci** [comment]
I am sorry I didn't close this earlier. Your suggestions helped to fix the issue. Thank you so much of helping me out

**Comment by AVHopp** [comment]
No problem and happy that we could help 😄
