### ISSUE TITLE
Error in match mode when trying to take mean of bounds

### ISSUE THREAD

**Issue by brandon-holt** [emdgroup/baybe#207]
Hi, 

When running a simulation in match mode, the code fails when trying to generate results because it attempts to take a np.mean() of the Interval(), returning error `TypeError: unsupported operand type(s) for: 'Interval' and 'int'`

The error occurs on line 551 of simulation.py here 
```Python        
elif target.mode is TargetMode.MATCH:
    match_val = np.mean(target.bounds)
```

In the meantime just changing the line locally to

```Python
match_val = np.mean([target.bounds.lower, target.bounds.upper])
```

Assuming this is just from outdated code since you mentioned this was an old module in need of a refresh!

**Comment by AdrianSosic** [comment]
Hi @brandon-holt :wave: Again, thanks for the report ⭐ Your assumption is indeed correct – the core functionalities have been refactored quite extensively in the last couple of months and our simulation module is lagging completely behind. In fact, the bug you found is so obvious that it is even clearly reported by our type checker, but sadly the simulation module is the last bigger module for which the checker is still deactivated due to the pending overhaul.

That said, I'll try to push a hotfix PR tomorrow and also do at least a basic first cleanup these days that should kill most other bugs if there exist more. Hope that I can get the remaining bits fixed in the next 1-2 weeks 👍🏼

**Comment by brandon-holt** [comment]
Amazing, thanks as always!!

**Comment by brandon-holt** [comment]
When you look, would it be possible to check if there are any issues affecting the progress bar on simulations? I've been able to run many simulations now and get the results, but I'm never seeing a progress bar in .ipynb, just outputs that look something like
`WARNING:baybe.simulation:The lookup rows with indexes [62 86] seem to be duplicates regarding parameter values. Choosing a random one.`

**Comment by AdrianSosic** [comment]
Hi @brandon-holt, the PR with the hotfix is up. I'll wait with the merge until Monday though when both @AVHopp and @Scienfitz are available for review. Until then, you can access the fixed version via
```bash
pip install git+https://github.com/emdgroup/baybe.git@hotfix/match-mode-simulation
```
but please be aware that the branch is not stable until fully reviewed/merged.

I'll now have a look into the progress bar issue ...

**Comment by brandon-holt** [comment]
@AdrianSosic totally this works for now! Thank you!!

**Comment by AdrianSosic** [comment]
Perfect 😃 And BTW: turned out they were able to review already today, so everything is on `main` already.
