### ISSUE TITLE
Published docs use main instead of released version

### ISSUE THREAD

**Issue by monken** [emdgroup/baybe#222]
The docs at https://emdgroup.github.io/baybe/ seem to be built from the main branch instead of 0.8.2. The API has changed in main so the example on the front page no longer works with the version installed from pypi.

**Comment by AdrianSosic** [comment]
Hi @monken, in fact the current situation is even worse: the online version has temporarily been built via a manual workflow trigger, so it's even desynced from main. The problem is that we have no multiversion docs in place yet, and you are not the first one to run into this. I've kept pushing for this feature several times but the priority doesn't resonate as much in the team ...

@Scienfitz @AVHopp: Having a main page whose primary example doesn't work is really terrible 🙈 Given that @monken is now the nth person running into this issue and we'll always tap into other issues in the future, I'm absolutely for fixing this next week. Let's talk in the dev meeting how to handle it 🤓

**Comment by Scienfitz** [comment]
In this case we can easily identify the culprit :) <img width="997" alt="image" src="https://github.com/emdgroup/baybe/assets/17951239/217b9cd2-df2a-417f-b683-b571ce9bfb61">

We should finish the remaining things for `0.9.0` which imo we are 70-80% through with the development. This would resync the page too.

We could also republish the `0.8.2` version of the docs in the meantime.

I agree that the docs should finally be versioned asap, but imo no need to interfere `0.9.0` development for that, lets do it immediately afterwards

**Comment by AVHopp** [comment]
Then I'll start working on all of the stuff necessary for this asap, and will already start necessary preparations.

**Comment by Scienfitz** [comment]
The doc has been republished from `0.8.2` enabled by #230
